# Generated by Django 4.2.4 on 2023-10-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.CharField(default=False, verbose_name='админ2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.CharField(default=False, verbose_name='админ'),
        ),
    ]
