# Generated by Django 4.2.4 on 2023-11-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_verification_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verification_code',
            new_name='code',
        ),
    ]
