# Generated by Django 4.2.4 on 2023-11-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_verification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verification',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='статус учетной записи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.CharField(default=False, verbose_name='администратор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.CharField(default=False, verbose_name='суперпользователь'),
        ),
    ]
