# Generated by Django 4.2.4 on 2023-12-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254, verbose_name='почта')),
                ('client_fio', models.CharField(max_length=500, verbose_name='фио')),
                ('client_comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('client_fio',),
            },
        ),
        migrations.CreateModel(
            name='Log_Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime_last_attempt', models.DateTimeField(verbose_name='дата и время последней попытки')),
                ('status_attempt', models.CharField(choices=[('УСПЕШНО', 'УСПЕШНО'), ('НЕ УСПЕШНО', 'НЕ УСПЕШНО')], default='НЕ УСПЕШНО', verbose_name='статус попытки')),
                ('answer_mail_server', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера, если он был')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылки',
                'ordering': ('status_attempt',),
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='время рассылки')),
                ('frequency', models.IntegerField(verbose_name='периодичность')),
                ('mailing_status', models.CharField(blank=True, choices=[('завершена', 'завершена'), ('создана', 'создана'), ('создана', 'создана')], default='создана', null=True, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('frequency',),
            },
        ),
        migrations.CreateModel(
            name='Text_Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(verbose_name='тема письма')),
                ('body', models.CharField(verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение для рассылки',
                'verbose_name_plural': 'Сообщения для рассылки',
                'ordering': ('subject',),
            },
        ),
    ]
