# Generated by Django 4.2.4 on 2023-12-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log_mailing',
            old_name='name',
            new_name='mailing',
        ),
    ]
