# Generated by Django 4.2.4 on 2023-12-03 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailing_name_alter_mailing_mailing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_mailing',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_comment',
            field=models.CharField(max_length=500, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='name',
            field=models.CharField(verbose_name='название'),
        ),
    ]
