# Generated by Django 4.2.4 on 2023-09-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
