# Generated by Django 4.2.4 on 2023-09-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_create_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='../media/article/', verbose_name='фото'),
        ),
    ]
