# Generated by Django 4.2.4 on 2023-09-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, verbose_name='название')),
                ('category_description', models.CharField(max_length=150, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'название',
                'verbose_name_plural': 'названия',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='название')),
                ('product_description', models.CharField(max_length=150, verbose_name='описание')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='фото')),
                ('product_category', models.CharField(max_length=150, verbose_name='категория')),
                ('product_price', models.IntegerField(verbose_name='цена')),
                ('product_data_of_create', models.DateTimeField(verbose_name='дата создания')),
                ('product_data_of_last_chance', models.DateTimeField(verbose_name='дата посл изменения')),
            ],
            options={
                'verbose_name': 'название',
                'verbose_name_plural': 'названия',
                'ordering': ('product_price',),
            },
        ),
    ]
