# Generated by Django 4.2.4 on 2023-09-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=500, verbose_name='описание'),
        ),
    ]
