# Generated by Django 4.2.4 on 2023-09-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_data_of_create',
            new_name='product_created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_data_of_last_chance',
            new_name='product_updated_at',
        ),
    ]
