# Generated by Django 4.2.4 on 2023-09-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
