# Generated by Django 4.2.4 on 2023-10-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='indicates_the_current_version',
            new_name='is_current_version',
        ),
    ]
