# Generated by Django 4.2.4 on 2023-10-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_rename_indicates_the_current_version_version_is_current_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_current_version',
            field=models.BooleanField(default=True, verbose_name='признак версии'),
        ),
    ]
