# Generated by Django 4.2.4 on 2023-11-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_product_options_alter_version_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_price',), 'permissions': (('can_product_description', 'Can product_description post'),), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
