# Generated by Django 4.2.4 on 2023-11-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_price',), 'permissions': (('set_product_description', 'set product_description продукт'), ('set_product_category', 'set product_category продукт'), ('set_product_price', 'set product_price продукт')), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
