# Generated by Django 4.2.4 on 2023-12-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_price',), 'permissions': (('set_product_description', 'редактирование описания продукта'), ('set_product_category', 'редактирование категории продукт'), ('set_product_price', 'редактирования цены продукт')), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
